server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/magic_conch
    username: dev01
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

custom:
  file:
    profile-path: /image/profile
    profile-location: C:/Users/HaJooHyun/Desktop/img/profile
    tag-image-path: /image/tag
    tag-image-location: C:/Users/HaJooHyun/Desktop/img/tag