server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    context-path: /

spring:
  mvc:
    ignore-default-model-on-redirect: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/magic_conch?serverTimezone=Asia/Seoul
    # url: 사용할 DB URL ex)jdbc:mysql://host:port/db_name?options...
    username: dev01 # DB username
    password: 1234 # DB user pwd

  jpa:
    hibernate:
      ddl-auto: create # 초기 단계에서만 이용하고 추후 validate 추천
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
